title: Kenny Yue # your name (or website title) here
logo: "/images/IMG_2754.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc in Geological Engineering at MST | A Geospatial Data Analyst
  <br><br>
  Hi, I'm Kenny. 
  <br><br>
  I'm Geospatial Analyst and Machine learning engineer from Hong Kong and currently located in Vancouver, BC. <br>
  I'm interested in Remote Sensing and InSAR.<br>
  My background is in GIS, geography, and geology. I'm trying to getting
  <a href="https://www.linkedin.com/in/yuengohikenny/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
